name: Node.js CI
"on":
  push:
  pull_request:
    types:
      - opened
      - synchronize
env:
  DOCKER_IMAGE_NAME: yadhav/safe-settings
  #IMAGE_REGISTRY_URL: docker.pkg.github.com
  IMAGE_REGISTRY_URL: docker.io
  AZURE_RESOURCE_GROUP: aks-actions
  AZURE_AKS_CLUSTER: actionsAKSCluster
  AZURE_LOCATION: '"East US"'
  AZURE_AKS_NAMESPACE: default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - run: npm install
#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: yadhav/safe-settings
#          tag_with_ref: true
