name: Node.js CI
"on":
  push:
  pull_request:
    types:
      - opened
      - synchronize
env:
  DOCKER_IMAGE_NAME: yadhav/safe-settings
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_RESOURCE_GROUP: aks-actions
  AZURE_AKS_CLUSTER: actionsAKSCluster
  AZURE_LOCATION: '"East US"'

jobs:
  deploy-to-k8s:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_SERVICE_PRINCIPAL }}" # Azure credentials
          resource-group: ${{env.AZURE_RESOURCE_GROUP}}
          cluster-name: ${{env.AZURE_AKS_CLUSTER}}
        id: login
      - run: |
          kubectl get deployment
