name: Node.js CI
"on":
  push:
  pull_request:
    types:
      - opened
      - synchronize
env:
  DOCKER_IMAGE_NAME: yadhav/safe-settings
  #IMAGE_REGISTRY_URL: docker.pkg.github.com
  IMAGE_REGISTRY_URL: docker.io
  AZURE_RESOURCE_GROUP: aks-actions
  AZURE_AKS_CLUSTER: actionsAKSCluster
  AZURE_LOCATION: '"East US"'
  AZURE_AKS_NAMESPACE: default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - run: npm install
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 #         registry: ${{ env.IMAGE_REGISTRY_URL }} 
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags:  |
            yadhav/safe-settings:main-enterprise
#          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.pull_request.head.sha || github.sha }}
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: yadhav/safe-settings
#          tag_with_ref: true
      - name: Inspect
        run: |
          docker image inspect yadhav/safe-settings:main-enterprise
      - name: Test
        id: test
        run: |
          docker run -d -p 3000:3000 yadhav/safe-settings:main-enterprise
          sleep 5000
          curl http://localhost:3000
 
