name: Node.js CI
'on':
  push:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - run: npm install
      - run: npm test
